version: '2'
services:
  grafana-graphite-statsd:
    build: .
    image: metthal/grafana-graphite-statsd
    container_name: grafana-graphite-statsd
    ports:
      - '80:80'
      - '81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
      - ./log/supervisor:/var/log/supervisor
      - ./grafana/dashboards:/src/dashboards
      - ./grafana/datasources:/src/datasources
